# Composicao do programa de teste de uma lista genérica duplamente encadeada
# Este exemplo utiliza o arcabouço completo 

[Diretorios]

Nome        =  TesteLista
PathDefault =  ..\Ludo
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Ludo
h           =  ..\Ludo

[Modulos]
TestLis
Lista

[BuildInicio]
/OUT:..\Produto\TRAB2-3.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
