# Teste do módulo tabuleiro usando a biblioteca contendo o arcabouço

[Diretorios]

Nome        =  TesteTabuleiro
PathDefault =  ..\Ludo
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Ludo
h           =  ..\Ludo

[Modulos]
Tabuleiro
Circular
Lista
Jogador
testeTabuleiro

[BuildInicio]
/OUT:..\Produto\TesteTabuleiro.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
